version: '3.4'
services:
  bitcoind:
    image: kylemanna/bitcoind
    volumes:
      - ./bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf

  postgres-alice:
    restart: unless-stopped
    image: postgres
    environment:
      POSTGRES_DB: eclair
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

  postgres-bob:
    restart: unless-stopped
    image: postgres
    environment:
      POSTGRES_DB: eclair
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

  eclair-alice:
    restart: unless-stopped
    image: acinq/eclair:release-0.6.1.SNAPSHOT-sqlite-wal-mode-sig-chaindir-mkdirs
    depends_on:
      - bitcoind
      - postgres-alice
    volumes:
      - ./eclair/eclair.conf:/data/eclair.conf
      - ./eclair/logback.xml:/data/logback.xml
    environment:
      JAVA_OPTS: -Dlogback.configurationFile=/data/logback.xml -Declair.db.driver=postgres -Declair.db.postgres.host=postgres-alice

  eclair-bob:
    restart: unless-stopped
    image: acinq/eclair:release-0.6.1.SNAPSHOT-sqlite-wal-mode-sig-chaindir-mkdirs
    depends_on:
      - bitcoind
      - postgres-bob
    volumes:
      - ./eclair/eclair.conf:/data/eclair.conf
      - ./eclair/logback.xml:/data/logback.xml
    environment:
      JAVA_OPTS: -Dlogback.configurationFile=/data/logback.xml -Declair.db.driver=postgres -Declair.db.postgres.host=postgres-bob

  loadtest:
     build: loadtest
     volumes:
       - ./${LOADTEST_CONFIG_FILE}:/loadtest.yml
